# -*- coding: utf-8 -*-
"""crewai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1kt14Hg9wRi5LW9FsiHOfaq935ZPzhb

**AI Agent using CrewAI and Amazon Nova Premier**

Use case : AI Candidate Screening.

This agent help you analyze CV against job requirements, give result for the next step of the recruitment process and create interview question.
"""

# Install CrewAI and AWS
!pip install python-dotenv packaging crewai pypdf boto3

import os
# Load environment and save AWS token
from dotenv import load_dotenv
load_dotenv("awskey.txt")
# Get AWS access key, AWS secret key and AWS region
accesskey = os.getenv("AWS_ACCESS_KEY")
secretkey = os.getenv("AWS_SECRET_KEY")
region = os.getenv("AWS_REGION")

# Import CrewAI
from crewai import LLM, Agent, Task, Crew, Process

llm = LLM(
    model="bedrock/us.amazon.nova-premier-v1:0",
    temperature=0.0,
    aws_access_key_id=accesskey,
    aws_secret_access_key=secretkey,
    aws_region_name=region
)

"""**Structure of this AI Agent**

**User --> Extract CV --> Compare and Match between Requirements and CV --> Result to the next step of the recruitment process --> Create Interview Question --> End**

**Create CrewAI Agent**
"""

candidateScreeningAgent = Agent(
    role='Candidate Screening Agent',
    goal='Compare and match between job requirements and extracted of curriculum vitae then give result for next step of recruitment process.',
    backstory="""
    Compare match agent that make sure can compare and match between job requirements and extracted of curriculum vitae and give value from 0 until 10 to the next step of recruitment process.
    """,
    verbose=True,
    allow_delegation=False,
    llm=llm
)

"""**Create CrewAI Task**"""

candidateScreeningTask = Task(
    description="""
    You are a virtual human resources expert. You help me COMPARE and MATCH between {cv_data} and requirements like this :
    1. Work across the AI lifecycle: from data preparation and model development to evaluation and deployment.
    2. Fine-tune and integrate LLMs (like OpenAI and Claude) into ERP workflows.
    3. Build smart features such as recommendation engines, forecasting modules, NLP tools, and more.
    Preferred requirements :
    Develop and maintain scalable cloud-based AI solutions across multi-cloud platforms (AWS, GCP, Azure).
    After you compare and match, give value from 0 until 10 to the next step of recruitment process.
    After give value, create 3 interview questions about CV PDF file that already extracted.
    BUT if result are is LESS THAN 7 of 10, don't create interview questions.
    Otherwise, create 3 interview questions about CV PDF file that already extracted.
    Write output structure MUST like example this :
    """,
    expected_output="""
    MINIMAL REQUIREMENTS ANALYSIS :

    Requirement 1:

    Requirement n (n is the number of requirement):

    PREFERRED REQUIREMENTS ANALYSIS :

    OVERALL MATCH PERCENTAGE :

    Strengths:

    Potential Gaps:

    RESULT : ..... of 10

    QUESTION 1 : .....

    QUESTION 2 : .....

    QUESTION 3 : .....
    """,
    agent=candidateScreeningAgent
)

"""**Create CrewAI Crew**"""

candidate_screening_crew = Crew(
    agents=[candidateScreeningAgent],
    tasks=[candidateScreeningTask],
    verbose=True,
)

"""**Try upload first CV PDF file**"""

# Extract CV PDF file
from pypdf import PdfReader
reader = PdfReader("Always Winner CV.pdf")
page = reader.pages[0]
text = page.extract_text()
print(text)

result = candidate_screening_crew.kickoff(inputs={'cv_data': text})

print(result)

"""**Try upload second CV PDF file**"""

# Extract CV PDF file
from pypdf import PdfReader
reader = PdfReader("Sonny Wawwak CV.pdf")
page = reader.pages[0]
texted = page.extract_text()
print(texted)

result_2 = candidate_screening_crew.kickoff(inputs={'cv_data': texted})

print(result_2)

